export const stories = [
  {
    name: 'Trang Duong',
    href: '#',
    avatar: '/images/storiesAva/trangduong.jpg',
    imgStory: '/images/stories/trangduongStoryImg.jpg',
    seen: true,
  },
  {
    name: 'Quynh Nhu',
    href: '#',
    avatar: '/images/storiesAva/quynhnhu.jpg',
    imgStory: '/images/stories/quynhnhuStoryImg.jpg',
    seen: true,
  },
  {
    name: 'dieuhien',
    href: '#',
    avatar: '/images/storiesAva/dieuhien.jpg',
    imgStory: '/images/stories/dieuhienStoryImg.jpg',
    seen: false,
  },
  {
    name: 'Sofm',
    href: '#',
    avatar: '/images/storiesAva/sofm.jpg',
    imgStory: '/images/stories/sofmStoryImg.jpg',
    seen: true,
  },
  {
    name: 'Cai Nao cung Hay',
    href: '#',
    avatar: '/images/storiesAva/cainaocunghay.png',
    imgStory: '/images/stories/cainaocunghayStoryImg.jpg',
    seen: true,
  },
  {
    name: 'Love Japan',
    href: '#',
    avatar: '/images/storiesAva/lovejapan.jpg',
    imgStory: '/images/stories/lovejapanStoryImg.jpg',
    seen: false,
  },
  {
    name: 'BLIZbooks',
    href: '#',
    avatar: '/images/storiesAva/sach.jpg',
    imgStory: '/images/stories/sach.jpg',
    seen: true,
  },
  {
    name: 'Kim Chi Truong',
    href: '#',
    avatar: '/images/storiesAva/kimchitruong.jpg',
    imgStory: '/images/stories/kimchitruongStoryImg.jpg',
    seen: true,
  },
  {
    name: 'SuperCar Blondie',
    href: '#',
    avatar: '/images/storiesAva/supercar.jpg',
    imgStory: '/images/stories/supercarStoryImg.jpg',
    seen: false,
  },
  {
    name: 'Steve Harvey',
    href: '#',
    avatar: '/images/storiesAva/steve.jpg',
    imgStory: '/images/stories/steveStoryImg.jpg',
    seen: true,
  },
  {
    name: 'Lotte Cinema Hue',
    href: '#',
    avatar: '/images/storiesAva/lotte.jpg',
    imgStory: '/images/stories/lotteStoryImg.jpg',
    seen: false,
  },
  {
    name: 'Nguyen Duy Hung',
    href: '#',
    avatar: '/images/storiesAva/nguyenduyhung.jpg',
    imgStory: '/images/stories/nguyenduyhungStoryImg.jpg',
    seen: true,
  },
  {
    name: 'Crunchyroll',
    href: '#',
    avatar: '/images/storiesAva/crunchyroll.jpg',
    imgStory: '/images/stories/crunchyrollStoryImg.jpg',
    seen: false,
  },
  {
    name: 'Art Daily',
    href: '#',
    avatar: '/images/storiesAva/artdaily.jpg',
    imgStory: '/images/stories/artdailyStoryImg.jpg',
    seen: true,
  },
  {
    name: 'And Da Den',
    href: '#',
    avatar: '/images/storiesAva/anhdaden.jpg',
    imgStory: '/images/stories/anhdadenStoryImg.jpg',
    seen: false,
  },
  {
    name: 'Diem Quynh',
    href: '#',
    avatar: '/images/storiesAva/diemquynh.jpg',
    imgStory: '/images/stories/diemquynhStoryImg.jpg',
    seen: true,
  },
  {
    name: 'Sang Nguyen',
    href: '#',
    avatar: '/images/storiesAva/sangnguyen.jpg',
    imgStory: '/images/stories/sangnguyenStoryImg.jpg',
    seen: true,
  },
  {
    name: 'Quang Huy',
    href: '#',
    avatar: '/images/storiesAva/quanghuy.jpg',
    imgStory: '/images/stories/quanghuyStoryImg.jpg',
    seen: false,
  },
];
