import { ClerkProvider } from '@clerk/nextjs'
import NavBar from '@/components/navBar'
import  SideBar from '@/components/sideBar'
import './globals.css'
import { Inter } from 'next/font/google'
import WindowChat from '@/components/windowChat/WindowChat'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`${inter.className} box-border bg-secondary-clr text-neutral-700 dark:text-primary-text  `}>
          <NavBar />
          <SideBar />
          {children}
          <WindowChat/>
        </body>
      </html>
    </ClerkProvider>

  )
}
